language: objective-c

before_install:
  - . cmd/ci/travis/osx/before_install.sh
install:
  - . cmd/ci/travis/osx/install.sh
before_script:
  - . cmd/ci/travis/before_script.sh
script:
  - go build
after_script:
  - . cmd/ci/travis/osx/after_script.sh
cache:
  directories:
    - $QTDIR