language: objective-c
env: GOPATH="$HOME/.go_workspace"
before_install:
  - . cmd/ci/travis/osx/before_install.sh
install:
  - . cmd/ci/travis/osx/install.sh
before_script:
  - . cmd/ci/travis/osx/before_script.sh
script:
  - . cmd/ci/travis/osx/script.sh
after_script:
  - . cmd/ci/travis/osx/after_script.sh
cache:
  directories:
    - "/usr/local/opt/qt5"