version: '{branch} build{build}'
clone_folder: C:\projects\src\gopkg.in\qml.v1
environment:
  QTDIR: C:\Qt\5.4\mingw491_32
  MINGW: C:\Qt\Tools\mingw491_32
  PKGCONFIGLITE_VERSION: 0.28
#  MINGW_VERSION: 4.8.3.20150601
  GOPATH: C:\projects

  matrix:
  - platform: x86
    GOROOT: C:\go-x86
#  - platform: x64
#    MINGW: C:\tools\mingw64
matrix:
  allow_failures:
    - platform: x64
install:
- set PKG_CONFIG_PATH=%QTDIR%\lib\pkgconfig
- set CPATH=%QTDIR%\include;%MINGW%\include;
- set LIBRARY_PATH=%QTDIR%\lib;%MINGW%\lib;
- IF NOT exist "C:\ProgramData\chocolatey\lib\pkgconfiglite.%PKGCONFIGLITE_VERSION%\*.*" (echo pkgconfiglite not installed, so install it & cinst pkgconfiglite -version %PKGCONFIGLITE_VERSION%) ELSE (echo pkgconfiglite already installed)
#- IF "%Platform%" == "x64" (IF NOT exist "C:\tools\mingw64\*.*" (echo MinGW-w64 not installed, so install it & cinst mingw -version %MINGW_VERSION%) ELSE (echo MinGW-w64 already installed))
- set PATH=%GOROOT%\bin;%QTDIR%\bin;%MINGW%\bin;%PATH%
cache:
- C:\ProgramData\chocolatey\bin\pkg-config.exe -> appveyor.yml
- C:\ProgramData\chocolatey\lib\pkgconfiglite.%PKGCONFIGLITE_VERSION% -> appveyor.yml
#- C:\tools\mingw64 -> appveyor.yml
build_script:
- go build
on_failure:
- set
- go env